### ISSUE TITLE
Add REPL (or add it back/get it running in TED again)

### ISSUE THREAD

**Issue by SamuelHill** [ianhorswill/TED#8]
- [ ] Add REPL...

**Comment by ianhorswill** [comment]
Done.  Note that you now need to call simulation.Begin() after making a simulation and before making predicates.  Then call simulation.End() when you finish making predicates.  Having done that, you can say:

simulation.Repl.Query("SomeName", "Foo[x,y], Bar[y]")

and it will return a new table predicate called SomeName that computes that query.  It does not add it to the simulation, however.  We need to come up with some theory of how we keep track of what queries are still live and need to be recomputed each tick.  Otherwise, we may end up continuously computing every query you've ever run.
